var ruMessages = {
    title: `${serverName}::Бесплатный игровой сервер`,
    slogan: `от ${developerName} - качество, проверенное временем`,
    general: "Главная",
    aboutServer: "О сервере",
    registration: "Регистрация",
    contact: 'Контакты',
    files: "Файлы",
    statistic: "Статистика",
    forum: "Форум",
    fieldsCannotEmpty: 'Поля не должны быть пустыми!',
    waiting: 'Подождите ...',
    loginExists: 'Логин уже существует!',
    accountCreated: 'Аккаунт создан!',
    accountNotExists: 'Аккаунт не существует!',
    incorrectPassword: 'Не верный пароль!',
    incorrerctOldPassword: 'Неверный старый пароль!',
    invalidLogin: 'Неверный логин!',
    emailExists: 'Такой е-мейл уже существует',
    passwordsNotMatch: 'Пароли не совпадают!',
    passwordChanged: 'Пароль изменен',
    checkEmail: 'Проверьте почту :)',
    mesageCanOnlyRegisteredUsers: 'Сообщения могут отправлять только зарегистрированые пользователи',
    incorrectEmail: 'Не корректный e-mail:(...',
    somthingWrong: 'Что-то пошло не так(...',
    botsAction: 'Подозрение на бот-активность(...',
    passwordChanging: 'Смена пароля',
    forgotPassword: 'Забыли пароль',
    password: 'Пароль',
    oldPassword: 'Старый пароль',
    newPassword: 'Новый пароль',
    repeatePassword: 'Повторить пароль',
    back: 'Назад',
    change: 'Сменить',
    loginName: 'Логин',
    enter: 'Войти',
    email: 'E-mail',
    send: 'Отправить',
    messageSended: 'Сообщение отправлено!',
    messageNotSended: 'Письмо не отправлено :( ...',
    invalidAnswer: 'Неверный ответ!',
    news: 'НОВОСТИ ПРОЕКТА',
    dataCenter: 'Датацентр',
    publishingIn: 'Опубликовано в',
    readMore: 'Подробнее ...',
    personalCabinet: 'ЛИЧНЫЙ КАБИНЕТ',
    newsCaption: 'Заголовок',
    forumMessages: 'СЛУХИ НА ФОРУМЕ',
    exit: 'Выход',
    welcome: 'Приветствуем',
    license: 'ДАННЫЙ СЕРВЕР ЯВЛЯЕТСЯ ТЕСТОВЫМ ВАРИАНТОМ ИГРЫ LINEAGE II И ПРЕДНАЗНАЧЕН ТОЛЬКО ДЛЯ ОЗНАКОМЛЕНИЯ ИГРОКОВ. ВСЕ ПРАВА ПРИНАДЛЕЖАТ КОМПАНИИ NCSOFT.',
    rates: 'Рейты',
    selectIntoTop: 'Отбор в ТОП',
    selectIntoTopDescription: 'Проводится автоматически. Необходимое условие - получения статуса дворянина. Далеее сортировка происходит от наибольшего количества проведенного времени в игре. Отобранные в "десятку" еженедельно будут получать вознаграждение в виде Адены.',
    common: 'Общее',
    commonDescription: 'Броня, оружие, бижа с "Д" - до "Дино" сэтов, патроны - возможно покупать в комьюнити шопе. Пожелания, предложения, отчет по багам присылайте используя форму разделе "Контакты". Приятного геймплея!:)',
    ourCommunitys: 'Наши сообщества в социальных сетях',
    contactsForm: 'Форма для связи',
    fullName: 'Логин',
    emailForFeedback: 'Е-мейл (для обратной связи)',
    messagesText: 'Текст сообщения',
    accounts: 'Аккаунтов',
    characters: 'Персонажей',
    nobleses: 'Дворян',
    heroes: 'Героев',
    gameMasters: 'Гейм мастеров',
    clans: 'Кланы',
    allys: 'Альянсов',
    top10chars: 'Тор 10 персонажей',
    charName: 'Игровой ник',
    charClass: 'Класс',
    charSex: 'Пол',
    clanName: 'Название клана',
    gameTime: 'Время в игре',
    lvl: 'Ур.',
    leader: 'Лидер',
    reputation: 'Репутация',
    midLvl: 'Ср.ур',
    ally: 'Альянс',
    castles: 'Замки',
    castleName: 'Название замка',
    owner: 'Владелец',
    tax: 'Ставка налога',
    treasure: 'Казна',
    siegeDate: 'Дата осады',
    forts: 'Форты',
    fortName: 'Название форта'
}